@import hexlet.code.dto.urls.UrlsPage
@param UrlsPage page

<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Expected description">
    <title>Page analyzer project</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">

</head>
<body>
    <h1>Список добавленных URL</h1>
</body>
`
)